# Based on: https://gist.github.com/palewire/12c4b2b974ef735d22da7493cf7f4d37

name: Build and push to Artifact Registry

on:
  push:

env:
  PROJECT_ID: moderate-common
  GAR_LOCATION: europe-west1
  GAR_REPO: moderate-images
  IMAGE_NAME: moderate-docs

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3.3.0

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          # e.g. - my-service-account@my-project.iam.gserviceaccount.com
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          access_token_lifetime: 900s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v3.3.1
        with:
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.short_ref }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:latest
